/* qdl-en.js — Reçete ve Spesifikasyon (URS): EN modunda Türkçe kalan arayüz metinleri (qdl-ceviri.js). 25.09.2026 */
window.QDL_EN = {
  /* 25.09.2026 spesifikasyon formu + seçim listeleri + bileşik hammadde */
  "Gıdanın Adı *": "Food Name *",
  "Net Miktar": "Net Quantity",
  "Tavsiye Edilen/Son Tüketim Tarihi": "Best Before / Use By",
  "Muhafaza/Depolama Koşulları": "Storage Conditions",
  "İşletme Adı ve Adresi": "Business Name and Address",
  "Menşei Ülke": "Country of Origin",
  "Raf Ömrü": "Shelf Life",
  "gün": "days",
  "ay": "months",
  "yıl": "years",
  "Ürün Ölçüsü": "Product Dimensions",
  "(opsiyonel — ör. 20 × 12 × 5 cm, Ø 8 cm)": "(optional — e.g. 20 × 12 × 5 cm, Ø 8 cm)",
  "Gıda Güvenliği / BRCGS Ek Bilgileri": "Food Safety / BRCGS Additional Information",
  "Hedef Tüketici Grubu": "Target Consumer Group",
  "Taşıma Koşulları": "Transport Conditions",
  "Alerjen Beyanı": "Allergen Declaration",
  "reçeteden otomatik doldur": "auto-fill from recipe",
  "Çapraz Bulaşma Riski": "Cross-Contamination Risk",
  "Net Miktar / Palet Seçenekleri": "Net Quantity / Pallet Options",
  "(ör. 500 g · 1 kg · 5 kg — her biri için ayrı palet ya da dökme gönderim; listeler Ayarlar'dan genişletilir)": "(e.g. 500 g · 1 kg · 5 kg — separate pallet or bulk shipment for each; lists are extended in Settings)",
  "+ Gramaj/Palet Ekle": "+ Add Quantity/Pallet",
  "Ambalaj Tipleri": "Packaging Types",
  "(birden çok seçilebilir)": "(multiple allowed)",
  "+ Ambalaj Seçeneği Ekle": "+ Add Packaging Option",
  "Ambalaj Spesifikasyonu (boyut/katman detayı)": "Packaging Specification (size/layer details)",
  "TGK Madde 35 — Beslenme Bildirimi (100 g/ml başına)": "Nutrition Declaration (per 100 g/ml)",
  "🤖 AI ile Oluştur": "🤖 Generate with AI",
  "Enerji (kcal)": "Energy (kcal)",
  "Yağ (g)": "Fat (g)",
  "Doymuş Yağ (g)": "Saturated Fat (g)",
  "Trans Yağ (g)": "Trans Fat (g)",
  "Karbonhidrat (g)": "Carbohydrate (g)",
  "Şeker (g)": "Sugars (g)",
  "Protein (g)": "Protein (g)",
  "Tuz (g)": "Salt (g)",
  "Fiziksel-Kimyasal Parametreler": "Physical-Chemical Parameters",
  "Mikrobiyolojik Parametreler": "Microbiological Parameters",
  "(ör. Nem — Max 10,5 % / Protein — Min %10)": "(e.g. Moisture — Max 10.5 % / Protein — Min 10%)",
  "+ Parametre Ekle": "+ Add Parameter",
  "Ek Not (opsiyonel, serbest metin)": "Additional Note (optional, free text)",
  "Duyusal Kriterler": "Sensory Criteria",
  "+ Kriter Ekle": "+ Add Criterion",
  "Yasal Dayanaklar": "Legal References",
  "(bu spesifikasyonun uyduğu mevzuat/tebliğler)": "(regulations this specification complies with)",
  "+ Boş Ekle": "+ Add Blank",
  "Ürün Görselleri": "Product Images",
  "Yükle": "Upload",
  "Müşteri Spesifikasyonları": "Customer Specifications",
  "(müşterinin gönderdiği PDF/Word/Excel istek/spesifikasyon dosyaları)": "(PDF/Word/Excel request/specification files sent by the customer)",
  "Özel Alanlar": "Custom Fields",
  "(ürün kategorisine göre ek bilgi — ör. raf ömrü testi, özel müşteri şartı)": "(extra information by product category — e.g. shelf-life test, special customer requirement)",
  "+ Özel Alan Ekle": "+ Add Custom Field",
  "Onay Bilgisi": "Approval Information",
  "Kayıt Bilgisi": "Record Information",
  "Onaylayan Unvanı": "Approver Title",
  "(Onayla ve Kaydet'e basarken zorunlu — ör. Kalite Müdürü, Ar-Ge Sorumlusu)": "(required when pressing Approve and Save — e.g. Quality Manager, R&D Lead)",
  "Bu kaydetmede ne değişti? (opsiyonel not)": "What changed in this save? (optional note)",
  "Versiyon Geçmişi": "Version History",
  "Küçük alan güncellemesi.": "Minor field update.",
  "İlk oluşturma.": "Initial creation.",
  "🖨 PDF / Yazdır": "🖨 PDF / Print",
  "Taslak Olarak Kaydet": "Save as Draft",
  "Onayla ve Kaydet": "Approve and Save",
  "ör. 500 g": "e.g. 500 g",
  "ör. Üretimden itibaren 12 ay": "e.g. 12 months from production",
  "ör. Serin ve kuru yerde saklayınız": "e.g. Store in a cool, dry place",
  "ör. Genel tüketici / Çocuk / Alerjik hassas grup": "e.g. General consumers / Children / Allergy-sensitive",
  "ör. 4°C altında soğuk zincirle taşınmalıdır": "e.g. Must be transported in cold chain below 4°C",
  "Kriter (ör. Tat)": "Criterion (e.g. Taste)",
  "Açıklama (ör. Karakteristik, yabancı tat yok)": "Description (e.g. Characteristic, no foreign taste)",
  "Kaldır": "Remove",
  "ör. Kalite Müdürü": "e.g. Quality Manager",
  "ör. Beslenme bildirimi laboratuvar sonucuna göre güncellendi": "e.g. Nutrition declaration updated per lab results",
  "Bu matris ürünlerin reçetelerinde işaretlenen alerjenlerden CANLI olarak hesaplanır — reçete güncellenince otomatik yansır.": "This matrix is calculated LIVE from allergens marked in product recipes — updates automatically when a recipe changes.",
  "Bu bilgiler spesifikasyon PDF çıktısının üst bilgisinde (letterhead) ve yıllık gözden geçirme bildiriminde kullanılır.": "This information is used in the specification PDF letterhead and in the annual review notification.",
  "Seçim Listeleri": "Selection Lists",
  "+ Ekle": "+ Add",
  "Birimler": "Units",
  "Paket Ölçüleri / Net Miktarlar": "Pack Sizes / Net Quantities",
  "Palet Ölçüleri / Gönderim Şekli": "Pallet Sizes / Shipping Method",
  "Dökme (paletsiz)": "Bulk (no pallet)",
  "Yeni ekle…": "Add new…",
  "Net miktar / paket": "Net quantity / pack",
  "Palet ölçüsü / dökme": "Pallet size / bulk",
  "Palette Adet": "Units per Pallet",
  "Not (ops.)": "Note (opt.)",
  "Ambalaj tipi": "Packaging type",
  "Birim": "Unit",
  "Parametre (ör. Nem)": "Parameter (e.g. Moisture)",
  "Min (ör. 10)": "Min (e.g. 10)",
  "Max (ör. 10,5)": "Max (e.g. 10.5)",
  "— seçin —": "— select —",
  "Kraft kağıt torba": "Kraft paper bag",
  "PE torba": "PE bag",
  "PP dokuma çuval": "PP woven sack",
  "Metalize film": "Metallised film",
  "Karton kutu": "Carton box",
  "Oluklu koli": "Corrugated case",
  "Cam kavanoz": "Glass jar",
  "PET şişe": "PET bottle",
  "Teneke kutu": "Tin can",
  "Vakum ambalaj": "Vacuum pack",
  "İçecekler": "Beverages",
  "Un ve Tahıl Ürünleri": "Flour and Cereal Products",
  "Alt Bileşenler": "Sub-ingredients",
  "+ Alt Bileşen Ekle": "+ Add Sub-ingredient",
  "Alt bileşen adı": "Sub-ingredient name",
  "% (hammadde içinde)": "% (within ingredient)",
  "İçindekiler (azalan ağırlık sırasıyla)": "Ingredients (in descending order of weight)",
  "Hammadde Adı *": "Ingredient Name *",
  "Oran (%)": "Ratio (%)",
  "Hammadde Ekle": "Add Ingredient",
  "Hammaddeyi Düzenle": "Edit Ingredient",
  "Tedarikçi (opsiyonel — bilgi amaçlı, portal/giriş yok)": "Supplier (optional — informational, no portal/login)",
  "Not (opsiyonel)": "Note (optional)",
  "İçerdiği Alerjenler (varsa)": "Allergens Contained (if any)",
  "+ Hammadde Ekle": "+ Add Ingredient",
  "Hammadde": "Ingredient",
  "Oran": "Ratio",
  "1 Ton İçin": "Per 1 Tonne",
  "Tedarikçi": "Supplier",
  "Proses": "Process",
  "Spesifikasyon — Yazdırma Görünümü": "Specification — Print View",
  "Ürün Adı *": "Product Name *",
  "Yeni Ürün": "New Product",
  "Ürünü Düzenle": "Edit Product",
  "Ürünler": "Products",
  "Reçeteler": "Recipes",
  "Spesifikasyonlar": "Specifications",
  "Alerjen Matrisi": "Allergen Matrix",
  "Ayarlar": "Settings",
  "Anasayfa": "Home",
  "GENEL": "GENERAL",
  "ÜRÜN YÖNETİMİ": "PRODUCT MANAGEMENT",
  "SİSTEM": "SYSTEM",
  "Genel": "General",
  "Ürün Yönetimi": "Product Management",
  "Sistem": "System",
  'Reçete ve Spesifikasyon': 'Recipe & Specification', '🌙 Koyu / ☀ Açık': '🌙 Dark / ☀ Light', '🧭 Turu göster': '🧭 Show tour', '⏻ Çıkış Yap': '⏻ Sign Out',
  'Tüm Sertifikalar →': 'All Certificates →', 'Ürün': 'Product', 'Tür': 'Type', 'Geçerlilik Bitiş': 'Valid Until', 'Durum': 'Status',
  'Süresi Doldu': 'Expired', 'Süresi Yaklaşıyor': 'Expiring Soon', 'Geçerli': 'Valid', 'Son Güncellenen Reçeteler': 'Recently Updated Recipes', 'Tüm Reçeteler →': 'All Recipes →',
  'Hammadde Sayısı': 'Number of Ingredients', 'Alerjenler': 'Allergens', 'Menüyü aç/kapat': 'Toggle menu', 'Menü': 'Menu', 'Listeyi aç': 'Open list',
  'Kategori': 'Category', 'Reçete': 'Recipe', 'Spesifikasyon': 'Specification', 'Aktif': 'Active', 'Pasif': 'Inactive', '(görüntüle)': '(view)', 'Onaylı': 'Approved', 'Taslak': 'Draft',
  '+ Spesifikasyon Oluştur': '+ Create Specification',
  'Reçetedeki hammaddeleri TGK kuralı gereği': 'As required by the Turkish Food Codex, enter the recipe ingredients in',
  'azalan ağırlık sırasıyla': 'descending order of weight',
  'girin — bu sıra, spesifikasyondaki "içindekiler" listesinin sırasını belirler.': '— this order determines the order of the "ingredients" list in the specification.',
  'Toplam Oran': 'Total Ratio', 'Yok': 'None', 'Gıda Adı': 'Food Name', 'Spec Kodu': 'Spec Code', 'Versiyon': 'Version', 'Son Güncelleme': 'Last Update',
  'Gluten içeren tahıllar': 'Cereals containing gluten', 'Kabuklu su ürünleri': 'Crustaceans', 'Yumurta': 'Eggs', 'Balık': 'Fish', 'Yerfıstığı': 'Peanuts', 'Soya': 'Soybeans',
  'Süt (laktoz dahil)': 'Milk (including lactose)', 'Sert kabuklu meyveler': 'Tree nuts', 'Kereviz': 'Celery', 'Hardal': 'Mustard', 'Susam': 'Sesame',
  'Kükürt dioksit ve sülfitler': 'Sulphur dioxide and sulphites', 'Acı bakla (Lupin)': 'Lupin', 'Yumuşakçalar': 'Molluscs',
  '+ Sertifika Ekle': '+ Add Certificate', 'Firma Bilgileri': 'Company Information', 'Logo yok': 'No logo', 'Logo Yükle': 'Upload Logo', 'Firma Adı': 'Company Name',
  'Yıllık Gözden Geçirme Bildirimi': 'Annual Review Notification', 'Üst Yönetici Adı': 'Top Manager Name', 'Üst Yönetici E-postası': 'Top Manager Email', 'Kaydet': 'Save', 'Vazgeç': 'Cancel',
  'onaylar süresi geldiğinde bilgilendirilir': 'is notified when approvals are due',
  'Filtre:': 'Filter:', '✕ Filtreyi kaldır': '✕ Clear filter', 'Aktif ürünler': 'Active products', 'Reçetesi olan ürünler': 'Products with a recipe',
  'Onaylı spesifikasyonlar': 'Approved specifications', 'Taslak spesifikasyonlar': 'Draft specifications', 'Alerjen içeren ürünler': 'Products with allergens',
  'Geçerli olmayan / süresi yaklaşan sertifikalar': 'Invalid / expiring certificates',
  'Ürün detayını aç': 'Open product details', 'Açıklama': 'Description', 'Girilmedi': 'Not entered', 'Sertifikalar': 'Certificates', '✏️ Düzenle': '✏️ Edit', 'Kapat': 'Close', 'Spesifikasyonu Aç →': 'Open Specification →',
  'İşletme Kayıt No': 'Business Registration No', 'İşletme Onay No': 'Business Approval No', 'İşletme Kayıt / Onay No': 'Business Registration / Approval No', 'Önceki toplantıdan otomatik önerildi, değiştirebilirsiniz.': 'Suggested from the previous meeting; you can change it.'
};
window.QDL_EN_RE = [
  [/^(\d+) hammadde$/, '$1 ingredients'],
  [/^Spesifikasyon — (.+)$/, 'Specification — $1'],
  [/^(.+) tarafından (\S+ \S+) tarihinde onaylandı\.$/, 'Approved by $1 on $2.'],
  [/^Oluşturulma: (\S+) · Son Revizyon: (\S+)$/, 'Created: $1 · Last Revision: $2'],
  [/^ör\. (.+)$/, 'e.g. $1'],
  [/^\+ Türk Gıda Kodeksi (.+)$/, '+ Turkish Food Codex $1'],
  [/^— \[E-posta linki ile reddedildi\]$/, '— [Rejected via e-mail link]']
];
